#!/bin/bash
# GENERATED by nb2slurm for the 'monte_carlo_pi' workflow.
#
# Cancels the jobs listed in jobs.txt by their job name (one subject per line).
set -euo pipefail

JOBS_FILE="${1:-scripts/jobs.txt}"

while read -r n_samples seed _rest; do
    [ -z "${n_samples}" ] && continue
    case "${n_samples}" in \#*) continue ;; esac
    key="${n_samples}_${seed}"
    scancel --name="$key" && echo "cancelled $key"
done < "$JOBS_FILE"
