#!/bin/bash
# GENERATED by nb2slurm for the 'monte_carlo_pi' workflow.
#
# The THROTTLED submitter: like submit_batch.sh, but caps how many jobs run at
# once to 0 (using SLURM 'afterany' dependencies). Use this for big
# runs where you don't want to flood the queue. For the simple all-at-once
# version, see submit_batch.sh.
#
# Reads scripts/jobs.txt (generated from jobs.json); each line holds: n_samples seed
set -euo pipefail

JOBS_FILE="${1:-scripts/jobs.txt}"
CONCURRENCY=0
jobids=()

while read -r n_samples seed _rest; do
    [ -z "${n_samples}" ] && continue        # skip blank lines
    case "${n_samples}" in \#*) continue ;; esac  # skip comments

    key="${n_samples}_${seed}"
    outdir="output/${n_samples}/${seed}"
    mkdir -p "$outdir"

    dep_args=()
    if (( CONCURRENCY > 0 && ${#jobids[@]} >= CONCURRENCY )); then
        dep_args=(--dependency=afterany:"${jobids[-CONCURRENCY]}")
    fi

    jobid=$(sbatch --parsable "${dep_args[@]}" \
        --job-name="$key" \
        --output="$outdir/$key.out" \
        --error="$outdir/$key.err" \
        --export=ALL,N_SAMPLES=${n_samples},SEED=${seed} \
        scripts/job.slurm)

    jobids+=("$jobid")
    echo "submitted $key -> $jobid"
done < "$JOBS_FILE"
