#!/bin/bash
# GENERATED by nb2slurm for the 'monte_carlo_pi' workflow.
#
# The SIMPLE submitter: it sends every job to SLURM at once, with no limit on how
# many run at the same time. This is the easy one to read.
#   * Use this when you're happy to let SLURM queue everything.
#   * Use submit_jobs.sh instead if you need to cap how many run concurrently.
#
# It reads scripts/jobs.txt, which nb2slurm generates from jobs.json.
# Each line of that file holds the values: n_samples seed

set -euo pipefail

# Go through scripts/jobs.txt one line at a time. `read` splits each line on
# spaces and puts the pieces into these variables: n_samples seed
while read -r n_samples seed; do

    # Skip empty lines, and the header line (it starts with a '#').
    [ -z "${n_samples}" ] && continue
    case "${n_samples}" in \#*) continue ;; esac

    # Build a short job name and the output folder for this job, e.g.
    #   name   = NL_123_ssp126
    #   outdir = runs/NL/123/ssp126
    name="${n_samples}_${seed}"
    outdir="output/${n_samples}/${seed}"
    mkdir -p "$outdir"

    # Submit one job. --export hands the values to the SLURM job script.
    sbatch \
        --job-name="$name" \
        --output="$outdir/$name.out" \
        --error="$outdir/$name.err" \
        --export=ALL,N_SAMPLES=${n_samples},SEED=${seed} \
        scripts/job.slurm

    echo "submitted $name"

done < scripts/jobs.txt
